### ISSUE TITLE
Make it easier to see what was selected

### ISSUE THREAD

**Issue by elescamilla** [lanl/Memento-Tracer-Extention#8] opened 2022-08-26 23:35 UTC
With the current implementation, it is not easy to determine what has been selected. For example, sometimes the "click" option indicates that multiple things were selected and belong to the class. However, only one item will be included in the trace.

For this issue, investigate options to improve clarity.

Definition of done: present options for improving clarity in what was selected for the trace.

**Comment by luda171** [comment] 2022-09-01 21:07
Again it depends on the use case.

**Comment by martinklein0815** [comment] 2022-09-06 19:44
an example would help, IMO

**Comment by talyacooper** [comment] 2022-10-17 15:52
I think I worded the initial issue poorly (the problem is basically "not everything that is highlighted by the tool necessarily gets traced) but I wonder if it makes sense to change this issue to be about incorporating the trace-test tool/function into the extension (or could close this issue and make a separate one for that)

**Closed as completed** 2023-06-16 18:03 UTC
Labels: Importance 5
